const productController=require("../controllers/productController")
const express=require("express")
const router=express.Router()
router.get("/",productController.getProducts)
router.get("/:_id",productController.getProductById)
router.get("/getByName",productController.getProductByName)
router.post("/",productController.addProduct)
router.put("/",productController.updateProduct)
router.delete("/:_id",productController.deleteProduct)
module.exports=router